name: ci

on:
  - pull_request
  - workflow_dispatch

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".tool-versions"

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - id: cache-node-modules
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - run: pnpm sync-design-tokens

      - run: pnpm format

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".tool-versions"

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - id: cache-node-modules
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - run: pnpm t

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".tool-versions"

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - id: cache-node-modules
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - run: pnpm lint
